---
title: "caregiver-analysis"
author: "Angela Wang"
date: "August 4, 2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## R Markdown

```{r load-packages, message=FALSE}
library(tidyverse)
library(readr)
library(broom)
library(knitr)
library(skimr)
```

# PHQ-9

```{r load-data-phq9}
phq9 <- read_csv("Caregiver PHQ9.csv")
phq9 <- as.tibble(phq9)
```

## Exploratory Graphs 
```{r graphs-phq9}

ggplot(data = phq9, aes(x = `Total: Used to see severity of depressive disorder`)) + 
  geom_histogram( bins = 10, color = "black", fill = "gray") +
  labs(title = "Depression Scores in Caregivers", x = "Total Depression Score")


ggplot(data = phq9, aes(x = `Depression Severity` )) + 
  geom_bar() +
  labs(title = "Frequency of Depression Severity in Caregivers", y = "Count")


ggplot(data=phq9, mapping = aes(fill= `Depression Severity`, x=`Gender`)) + 
  geom_bar(position="fill") +
  labs(title="Relationship between Depression Severity and Gender", y ="Proportion", x = "Gender", fill = "Depression Severity")


ggplot( data = phq9, aes( x = `Depression Severity`, y = `Age`, fill = `Depression Severity`)) + 
  geom_boxplot() + 
  labs(title = "Relationship between Depression Severity and Age")


ggplot( data = phq9, aes(x = `Age`, y =  `Total: Used to see severity of depressive disorder` )) +
  geom_smooth() +
  labs(title = "Relationship between Depression Severity and Age", x = "Age", y = "Total Depression Score")

ggplot( data = phq9, aes( x = `Depression Severity`, y = `Time in Ghar`, fill = `Depression Severity`)) + 
  geom_boxplot() + 
  labs(title = "Relationship between Depression Severity and Time in Ghar", y = "Time in Ghar (months)")

ggplot( data = phq9, aes(x = `Time in Ghar`, y = `Total: Used to see severity of depressive disorder`)) +
  geom_smooth() +
  labs(title = "Relationship between Depression Severity and Time in Ghar", x = "Time in Ghar", y = "Total Depression Score")
```

## Mean/Median/Range of Total Depression Scores
```{r sum-scores-phq9 }
summary(phq9$`Total: Used to see severity of depressive disorder`)
```

## Standard Deviation of Total Depression Scores
```{r sd-phq9}
sd(phq9$`Total: Used to see severity of depressive disorder`)
```

# GAD-7
```{r load-data-gad7}
gad7 <- read_csv("Caregiver GAD-7.csv")
gad7 <- as.tibble(gad7)
gad7 <- gad7[-c(29, 30), ]
view(gad7)
```

## Exploratory Graphs
```{r graphs-gad7}

ggplot(data = gad7, aes(x = `Scores`)) + 
  geom_histogram(bins = 10,color = "black", fill = "gray") +
  labs(title = "Anxiety Scores in Caregivers", x = "Total Anxiety Score", y = "Count")


ggplot(data = gad7, aes(x = `Anxiety Severity` )) + 
  geom_bar() +
  labs(title = "Frequency of Anxiety Severity in Caregivers", y = "Count")

ggplot(data= gad7, mapping = aes(fill= `Anxiety Severity`, x=`Gender`)) + 
  geom_bar(position="fill") +
  labs(title="Relationship between anxiety severity and gender", y ="Proportion", x = "Gender", fill = "Anxiety Severity")

ggplot( data = gad7, aes( x = `Anxiety Severity`, y = `Time in Ghar`, fill = `Anxiety Severity`)) + 
  geom_boxplot() + 
  labs(title = "Relationship between Depression Severity and Time in Ghar", y = "Time in Ghar (months)")

ggplot(data = gad7, aes(x = `Age`, y = `Scores`)) +
  geom_smooth() +
  labs(title = "Relationship between Age and Total Anxiety Scores", x= "Age", y = "Total Anxiety Scores")

ggplot( data = gad7, aes( x = `Anxiety Severity`, y = `Time in Ghar`, fill = `Anxiety Severity`)) + 
  geom_boxplot() + 
  labs(title = "Relationship between Anxiety Severity and Time in Ghar", y = "Time in Ghar (months)")

ggplot(data = gad7, aes(x = `Time in Ghar`, y = `Scores`)) +
  geom_smooth() +
  labs(title = "Relationship between Time in Ghar and Total Anxiety Scores", x= "Time in Ghar (Months)", y = "Total Anxiety Scores")
```

## Mean/Median/Range of Total Anxiety Scores
```{r sum-scores-gad7}
summary(gad7$`Scores`)
```

## Standard Deviation of Total Anxiety Scores
```{r sd-gad7}
sd(gad7$`Scores`)
```

# OBI

```{r load-data-OBI}
obi <- read_csv("Caregiver OBI.csv")
obi <- as.tibble(obi)
obi <- obi[-c(29, 30), ]
view(obi)
```

```{r graphs-obi}

ggplot(data = obi, aes(x = `Overall Sum`)) + 
  geom_histogram(bins = 10,color = "black", fill = "gray") +
  labs(title = "Overall Burnout Scores in Caregivers", x = "Overall Burnout Score", y = "Count")

ggplot(data = obi, aes(x = `Disengagement Mean`)) + 
  geom_histogram(bins = 10,color = "black", fill = "gray") +
  labs(title = "Mean Disengagement Scores in Caregivers", x = "Mean Disengagement Score", y = "Count")

ggplot(data = obi, aes(x = `Exhaustion Mean`)) + 
  geom_histogram(bins = 10,color = "black", fill = "gray") +
  labs(title = "Mean Exhaustion Scores in Caregivers", x = "Mean Exhaustion Score", y = "Count")

ggplot(data = obi, aes(x = `Gender`, y = `Overall Sum`, fill = `Gender`)) + 
  geom_boxplot() +
  labs(title = "Relationship between Overall Burnout Scores and Gender", x = "Overall Burnout Score", y = "Gender", fill = "Gender")

ggplot(data = obi, aes(x = `Gender`, y = `Disengagement Mean`, fill = `Gender`)) + 
  geom_boxplot() +
  labs(title = "Relationship between Mean Disengagement Scores and Gender", x = " Mean Disengagement Scores", y = "Gender", fill = "Gender")

ggplot(data = obi, aes(x = `Gender`, y = `Exhaustion Mean`, fill = `Gender`)) + 
  geom_boxplot() +
  labs(title = "Relationship between Mean Exhaustion Scores and Gender", x = " Mean Exhaustion Scores", y = "Gender", fill = "Gender")

ggplot(data = obi, aes(x = `Age`, y = `Overall Sum`)) +
  geom_smooth() +
  labs(title = "Relationship between Age and Overall Burnout Scores", x= "Age", y = "Overall Burnout Scores")

ggplot(data = obi, aes(x = `Age`, y = `Disengagement Mean`)) +
  geom_smooth() +
  labs(title = "Relationship between Age and Mean Disengagement Scores", x= "Age", y = "Mean Disengagement Scores")

ggplot(data = obi, aes(x = `Age`, y = `Exhaustion Mean`)) +
  geom_smooth() +
  labs(title = "Relationship between Age and Mean Exhaustion Scores", x= "Age", y = "Mean Exhaustion Scores")

ggplot(data = obi, aes(x = `Time in Ghar`, y = `Overall Sum`)) +
  geom_smooth() +
  labs(title = "Relationship between Time in Ghar and Overall Burnout Scores", x= "Time in Ghar (months)", y = "Overall Burnout Scores")

ggplot(data = obi, aes(x = `Time in Ghar`, y = `Disengagement Mean`)) +
  geom_smooth() +
  labs(title = "Relationship between Time in Ghar and Mean Disengagement Scores", x= "Time in Ghar(months)", y = "Mean Disengagement Scores")

ggplot(data = obi, aes(x = `Age`, y = `Exhaustion Mean`)) +
  geom_smooth() +
  labs(title = "Relationship between Age and Mean Exhaustion Scores", x= "Age", y = "Mean Exhaustion Scores")

```

## Mean/Median/Range of Total Burnout Scores
```{r sum-scores-obi}
summary(obi$`Overall Sum`)
```

## Standard Deviation of Total Anxiety Scores
```{r sd-obi}
sd(obi$`Overall Sum`)
```